# Paste into the Python visual on page 2.
# Generated by scripts/generate-pbip.py - edit there, not here.

# Power BI hands the fields you dropped in to this script as the
# pandas DataFrame `dataset`. It must finish by calling plt.show().
#
# Do NOT call matplotlib.use("Agg") here. Power BI sets up its own backend and
# hooks plt.show() to capture the figure; overriding the backend makes show() a
# no-op and the visual renders completely blank with no error.
import matplotlib.pyplot as plt

df = dataset.groupby("Category", as_index=False)["SalesAmount"].sum()
df = df.sort_values("SalesAmount")

fig, ax = plt.subplots(figsize=(8, 4.5))
bars = ax.barh(df["Category"], df["SalesAmount"], color="#1F4E79")
ax.set_xlabel("Revenue (USD)")
ax.set_title("Revenue by Category - built by Python in Power BI", fontsize=13)
ax.spines[["top", "right"]].set_visible(False)
for b, v in zip(bars, df["SalesAmount"]):
    ax.text(v, b.get_y() + b.get_height() / 2, f" ${v/1e6:.2f}M",
            va="center", fontsize=10, color="#1F4E79")
ax.set_xlim(0, df["SalesAmount"].max() * 1.18)
plt.tight_layout()
plt.show()
