# Paste into the R visual on page 4.
# Generated by scripts/generate-pbip.py - edit there, not here.

# auto.arima picks the model, then we forecast 6 periods.
# This is the demo that justifies R visuals: the built-in Power BI
# forecast cannot show you which ARIMA order it chose.
library(forecast)

d  <- dataset[order(dataset$MonthNumber), ]
ts_data <- ts(d$Revenue, frequency = 12)
fit <- auto.arima(ts_data)
fc  <- forecast(fit, h = 6)

par(mar = c(4, 4, 3, 1))
plot(fc,
     main = paste0("6-month revenue forecast - ARIMA(",
                   paste(arimaorder(fit), collapse = ","), ")"),
     xlab = "Period (year fraction, 12 = monthly)",
     ylab = "Revenue (USD)",
     col = "#1F4E79", fcol = "#C00000", flwd = 2)
grid(col = "#DDDDDD")
legend("topleft", bty = "n", cex = 0.9,
       legend = c("Actual", "Forecast + 80/95% CI"),
       col = c("#1F4E79", "#C00000"), lwd = 2)
