# Paste into the R visual on page 3.
# Generated by scripts/generate-pbip.py - edit there, not here.

# `dataset` is the data frame Power BI builds from the fields
# dropped into this visual.
library(ggplot2)

agg <- aggregate(SalesAmount ~ Category, data = dataset, FUN = sum)
agg$Label <- paste0("$", format(round(agg$SalesAmount / 1e6, 2), nsmall = 2), "M")

ggplot(agg, aes(x = reorder(Category, SalesAmount), y = SalesAmount)) +
  geom_col(fill = "#1F4E79", width = 0.65) +
  geom_text(aes(label = Label), hjust = -0.12, size = 4.2, colour = "#1F4E79") +
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.20))) +
  labs(title = "Revenue by Category - built by R (ggplot2)",
       x = NULL, y = "Revenue (USD)") +
  theme_minimal(base_size = 14) +
  theme(panel.grid.major.y = element_blank(),
        plot.title = element_text(colour = "#1F4E79", size = 14))
